sudo: false

# Travis CI does not currently support Python on Mac OS X
language: generic

os:
  - linux
#   - osx

env:
  - PYTHON_VERSION=2.7
#   - PYTHON_VERSION=3.4
#   - PYTHON_VERSION=3.5
  - PYTHON_VERSION=3.6

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      curl https://repo.continuum.io/miniconda/Miniconda${PYTHON_VERSION:0:1}-latest-MacOSX-x86_64.sh -o miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda${PYTHON_VERSION:0:1}-latest-Linux-x86_64.sh -O miniconda.sh;
    fi

  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  - conda create -q -n test-environment python=$PYTHON_VERSION
  - source activate test-environment

  - RGF_VER=$(head -n 1 rgf/VERSION)

install:
  - conda install -q numpy scipy nose pandas scikit-learn
  - python setup.py sdist --formats gztar
  - pip install dist/rgf_python-$RGF_VER.tar.gz -v

script:
  - python tests/test.py
  - pip uninstall -y rgf_python
  - python setup.py install
  - python tests/test.py

deploy:
  file_glob: true
  file: dist/*
  skip_cleanup: true
  draft: true
  provider: releases
  api-key:
    secure: "XMhFYMm4tVlVK4Bm76jnWgdZF8LPZTgbLsZDiPlkOnFvnmgTRSBjza8V8Ctj+gtzIQm/P5emNIQeJvUbZc7roHFR6hs6SfdRScX7ZchXLOpIZnFWvS37hH2JuWnZbXey6skqJpisz3mH+PrC503QtU/Bb5zMoPyBxws7cqpWkIU4KOucW1iwd2Ywi1qsaALrGmI9hXo0qGeCOOeNGesH76dLtEJ+og2qVdzpE9ywEz7FDCjhddgbu11imamYolI/l7tofJHxWvAr4nFRxaqN/soOKPSGroGfgVVDLCPheEsT4STpS0ueOCURUb1o8+gcFHXwORFZ72cWwm863LN/5oAh+LT02J62BkotCJUjrdeapYs2dpIvfQLQ6lsV1AwjQ72j+69q07V9DH/kYt5vW0cYXqJ4aHlTXymH/A6Mfddil9qfdmTlfiwRg6/fxiZcw6+slpXl6RDy/ugP1nAmGTH4ZQbiGM3fn/uLfJuDtwW/2YrT67oT8iUMu0GYDEB7u6P8IcdjKjPqNUk+Qk2/B5skZRPrIpvi3oPldgBpHttqg1ppLGa0cgU7KhjHceHa2gQj0aD7T+alQQp9rv2q0XdL3dlC9xx0sVGkI3P4ss6IDZ7tCRudPo3rbapuIh59CpYwH12vuBh7bchktiEYLZTcqtJfzb+ibRMXpeyvOqM="

  on:
    branch: master


